version: '3'

services:
  app:
    container_name: cached-score-api-app-1
    build: 
      context: .
      dockerfile: Dockerfile
    command: python src/app/api.py -l log.log
    ports:
      - '8080:8080'
    depends_on:
      - tarantool
    volumes:
      - ./logs/:/code/logs

  tarantool:
    build: 
      context: kv-store/
      dockerfile: Dockerfile
    ports:
      - '3301:3301'
    volumes:
      - ./db_tarantool/:/var/lib/tarantool
